/**
 * TEMPLATE: SEGUNDA OPINIÓN
 *
 * PITR™ — Protocolo de Inspección Técnica Remota
 * Template funcional con preguntas de ejemplo.
 *
 * Versión: 1.0.0
 * Servicio: segunda-opinion
 */

import type { InspectionTemplate } from "@/types/inspection";
import { QuestionType } from "@/types/inspection";

export const templateSegundaOpinion: InspectionTemplate = {
  id: "template-segunda-opinion",
  name: "Segunda Opinión de Certificado Energético",
  version: "1.0.0",
  service: "segunda-opinion",
  active: true,
  description:
    "Revisión técnica de un certificado energético existente para detectar errores y evaluar su fiabilidad.",
  order: 1,
  config: {
    allowDraft: true,
    allowResume: true,
    showProgress: true,
    showEstimatedTime: true,
    validateOnNext: true,
    requireAuth: false,
    freeNavigation: true,
    autoSaveInterval: 30,
    welcomeSection: "bienvenida",
    summarySection: "resumen",
    slots: {
      photography: true,
      ocr: true,
      ai: true,
      catastro: true,
      ce3x: true,
    },
  },
  sections: [
    // ── SECCIÓN 1: BIENVENIDA ──
    {
      id: "bienvenida",
      templateId: "template-segunda-opinion",
      name: "Bienvenida",
      description:
        "Antes de empezar, necesitamos algunos datos básicos para preparar tu inspección.",
      order: 1,
      required: true,
      estimatedTime: 5,
      questions: [
        {
          id: "bienvenida-nombre",
          sectionId: "bienvenida",
          type: QuestionType.TEXTO,
          text: "¿Cuál es tu nombre completo?",
          description: "Nombre de la persona que solicita la inspección.",
          placeholder: "Ej: María García López",
          required: true,
          order: 1,
        },
        {
          id: "bienvenida-email",
          sectionId: "bienvenida",
          type: QuestionType.EMAIL,
          text: "Correo electrónico de contacto",
          description: "Recibirás aquí el informe de resultados.",
          placeholder: "correo@ejemplo.com",
          required: true,
          validation: {
            pattern: "^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$",
            mensaje: "Introduce un email válido.",
          },
          order: 2,
        },
        {
          id: "bienvenida-telefono",
          sectionId: "bienvenida",
          type: QuestionType.TELEFONO,
          text: "Teléfono de contacto",
          placeholder: "600 000 000",
          required: false,
          order: 3,
        },
        {
          id: "bienvenida-tipo",
          sectionId: "bienvenida",
          type: QuestionType.RADIO,
          text: "¿Quién solicita esta segunda opinión?",
          required: true,
          order: 4,
          options: [
            { id: "bienv-tipo-1", label: "Particular — Soy el propietario", value: "particular" },
            { id: "bienv-tipo-2", label: "Comprador — Estoy comprando el inmueble", value: "comprador" },
            { id: "bienv-tipo-3", label: "Inmobiliaria o API", value: "inmobiliaria" },
            { id: "bienv-tipo-4", label: "Administrador de fincas", value: "admin_fincas" },
          ],
        },
      ],
    },

    // ── SECCIÓN 2: IDENTIFICACIÓN ──
    {
      id: "identificacion",
      templateId: "template-segunda-opinion",
      name: "Identificación del inmueble",
      description: "Datos básicos para identificar la vivienda o local.",
      order: 2,
      required: true,
      estimatedTime: 5,
      questions: [
        {
          id: "identificacion-direccion",
          sectionId: "identificacion",
          type: QuestionType.TEXTO,
          text: "Dirección completa del inmueble",
          description: "Calle, número, bloque, escalera, puerta.",
          placeholder: "Ej: Calle Mayor 12, 2º B",
          required: true,
          order: 1,
        },
        {
          id: "identificacion-ciudad",
          sectionId: "identificacion",
          type: QuestionType.TEXTO,
          text: "Ciudad o municipio",
          required: true,
          order: 2,
        },
        {
          id: "identificacion-cp",
          sectionId: "identificacion",
          type: QuestionType.TEXTO,
          text: "Código Postal",
          required: true,
          validation: { pattern: "^\\d{5}$", mensaje: "El CP debe tener 5 dígitos." },
          order: 3,
        },
        {
          id: "identificacion-tipo-inmueble",
          sectionId: "identificacion",
          type: QuestionType.SELECT,
          text: "Tipo de inmueble",
          required: true,
          order: 4,
          options: [
            { id: "id-tipo-1", label: "Piso", value: "piso" },
            { id: "id-tipo-2", label: "Casa unifamiliar", value: "unifamiliar" },
            { id: "id-tipo-3", label: "Ático", value: "atico" },
            { id: "id-tipo-4", label: "Bajo", value: "bajo" },
            { id: "id-tipo-5", label: "Local comercial", value: "local" },
            { id: "id-tipo-6", label: "Oficina", value: "oficina" },
          ],
        },
        {
          id: "identificacion-superficie",
          sectionId: "identificacion",
          type: QuestionType.NUMERO,
          text: "Superficie construida (m²)",
          placeholder: "75",
          required: true,
          order: 5,
        },
        {
          id: "identificacion-antiguedad",
          sectionId: "identificacion",
          type: QuestionType.SELECT,
          text: "¿Conoces el año de construcción?",
          required: false,
          order: 6,
          options: [
            { id: "id-ant-1", label: "Anterior a 1950", value: "pre_1950" },
            { id: "id-ant-2", label: "1950–1979", value: "1950_1979" },
            { id: "id-ant-3", label: "1980–2006", value: "1980_2006" },
            { id: "id-ant-4", label: "2007–2013", value: "2007_2013" },
            { id: "id-ant-5", label: "2014–2020", value: "2014_2020" },
            { id: "id-ant-6", label: "Posterior a 2020", value: "post_2020" },
            { id: "id-ant-7", label: "No lo sé", value: "desconocido" },
          ],
        },
      ],
    },

    // ── SECCIÓN 3: CATASTRO ──
    {
      id: "catastro",
      templateId: "template-segunda-opinion",
      name: "Referencia catastral",
      description: "La referencia catastral permite cruzar datos con el Catastro automáticamente.",
      order: 3,
      required: true,
      estimatedTime: 3,
      questions: [
        {
          id: "catastro-tiene-ref",
          sectionId: "catastro",
          type: QuestionType.RADIO,
          text: "¿Tienes la referencia catastral del inmueble?",
          description: "Aparece en el IBI, en la escritura o en la sede electrónica del Catastro.",
          required: true,
          order: 1,
          options: [
            { id: "cat-ref-1", label: "Sí, la tengo", value: "si_tengo" },
            { id: "cat-ref-2", label: "No la tengo pero puedo buscarla", value: "buscare" },
            { id: "cat-ref-3", label: "No la tengo y no puedo obtenerla", value: "no_tengo" },
          ],
        },
        {
          id: "catastro-referencia",
          sectionId: "catastro",
          type: QuestionType.REFERENCIA_CATASTRAL,
          text: "Referencia catastral",
          placeholder: "9876513VH2797F0001WX",
          required: true,
          validation: { formatoCatastral: true, mensaje: "La referencia catastral debe tener 14 o 20 dígitos." },
          condition: {
            preguntaId: "catastro-tiene-ref",
            operador: "contiene",
            valor: "tengo",
          },
          order: 2,
        },
        {
          id: "catastro-ubicacion",
          sectionId: "catastro",
          type: QuestionType.COORDENADAS,
          text: "Coordenadas del inmueble",
          description: "Puedes usar geolocalización automática.",
          placeholder: "41.3874, 2.1686",
          required: false,
          condition: {
            preguntaId: "catastro-tiene-ref",
            operador: "no_existe",
          },
          order: 3,
        },
      ],
    },

    // ── SECCIÓN 4: CERTIFICADO ──
    {
      id: "certificado",
      templateId: "template-segunda-opinion",
      name: "Certificado energético actual",
      description: "Información sobre el certificado que quieres revisar.",
      order: 4,
      required: true,
      estimatedTime: 5,
      questions: [
        {
          id: "certificado-tiene-pdf",
          sectionId: "certificado",
          type: QuestionType.RADIO,
          text: "¿Tienes el PDF del certificado energético?",
          required: true,
          order: 1,
          options: [
            { id: "cert-pdf-1", label: "Sí, lo tengo en PDF", value: "tengo_pdf" },
            { id: "cert-pdf-2", label: "Solo tengo la etiqueta energética", value: "solo_etiqueta" },
            { id: "cert-pdf-3", label: "No tengo el documento", value: "no_tengo" },
          ],
        },
        {
          id: "certificado-archivo",
          sectionId: "certificado",
          type: QuestionType.PDF,
          text: "Sube el archivo PDF del certificado",
          description: "El sistema extraerá los datos automáticamente.",
          required: true,
          validation: {
            maxFileSize: 20 * 1024 * 1024,
            allowedMimeTypes: ["application/pdf"],
          },
          condition: {
            preguntaId: "certificado-tiene-pdf",
            operador: "igual",
            valor: "tengo_pdf",
          },
          order: 2,
        },
        {
          id: "certificado-etiqueta-letra",
          sectionId: "certificado",
          type: QuestionType.SELECT,
          text: "¿Qué letra aparece en la etiqueta energética?",
          description: "Normalmente va de la A (más eficiente) a la G (menos eficiente).",
          required: false,
          condition: {
            preguntaId: "certificado-tiene-pdf",
            operador: "distinto",
            valor: "tengo_pdf",
          },
          order: 3,
          options: [
            { id: "cert-letra-1", label: "A", value: "A" },
            { id: "cert-letra-2", label: "B", value: "B" },
            { id: "cert-letra-3", label: "C", value: "C" },
            { id: "cert-letra-4", label: "D", value: "D" },
            { id: "cert-letra-5", label: "E", value: "E" },
            { id: "cert-letra-6", label: "F", value: "F" },
            { id: "cert-letra-7", label: "G", value: "G" },
            { id: "cert-letra-8", label: "No lo sé", value: "no_se" },
          ],
        },
        {
          id: "certificado-sospecha",
          sectionId: "certificado",
          type: QuestionType.TEXTAREA,
          text: "¿Por qué sospechas que tu certificado puede ser incorrecto?",
          description: "Cuéntanos qué te hace dudar de su fiabilidad.",
          placeholder: "Ej: La letra no coincide con la antigüedad del edificio, el técnico no visitó el inmueble...",
          required: false,
          order: 4,
        },
      ],
    },

    // ── SECCIÓN 5: VENTANAS ──
    {
      id: "ventanas",
      templateId: "template-segunda-opinion",
      name: "Ventanas y carpintería",
      description: "Las ventanas representan hasta el 30% de las pérdidas energéticas de una vivienda.",
      order: 5,
      required: true,
      estimatedTime: 5,
      questions: [
        {
          id: "ventanas-tipo",
          sectionId: "ventanas",
          type: QuestionType.SELECT,
          text: "¿Qué tipo de ventanas tiene el inmueble?",
          required: true,
          order: 1,
          options: [
            { id: "ven-tipo-1", label: "Aluminio con rotura de puente térmico", value: "aluminio_rpt" },
            { id: "ven-tipo-2", label: "Aluminio sin rotura", value: "aluminio_sin_rpt" },
            { id: "ven-tipo-3", label: "PVC", value: "pvc" },
            { id: "ven-tipo-4", label: "Madera", value: "madera" },
            { id: "ven-tipo-5", label: "Mixto", value: "mixto" },
            { id: "ven-tipo-6", label: "No lo sé", value: "desconocido" },
          ],
        },
        {
          id: "ventanas-vidrio",
          sectionId: "ventanas",
          type: QuestionType.SELECT,
          text: "Tipo de acristalamiento",
          required: false,
          order: 2,
          options: [
            { id: "ven-vidrio-1", label: "Simple (monolítico)", value: "simple" },
            { id: "ven-vidrio-2", label: "Doble con cámara de aire", value: "doble" },
            { id: "ven-vidrio-3", label: "Doble bajo emisivo", value: "doble_be" },
            { id: "ven-vidrio-4", label: "Triple", value: "triple" },
            { id: "ven-vidrio-5", label: "No lo sé", value: "desconocido" },
          ],
        },
        {
          id: "ventanas-estado",
          sectionId: "ventanas",
          type: QuestionType.RADIO,
          text: "¿En qué estado están las ventanas?",
          required: false,
          order: 3,
          options: [
            { id: "ven-est-1", label: "Buen estado — No se perciben corrientes", value: "bueno" },
            { id: "ven-est-2", label: "Regular — Alguna corriente o condensación", value: "regular" },
            { id: "ven-est-3", label: "Malo — Entra aire, no cierran bien", value: "malo" },
          ],
        },
      ],
    },

    // ── SECCIÓN 6: CUBIERTA ──
    {
      id: "cubierta",
      templateId: "template-segunda-opinion",
      name: "Cubierta y aislamiento",
      description: "La cubierta y el aislamiento determinan en gran medida la calificación energética.",
      order: 6,
      required: true,
      estimatedTime: 4,
      questions: [
        {
          id: "cubierta-posicion",
          sectionId: "cubierta",
          type: QuestionType.RADIO,
          text: "¿Qué posición ocupa la vivienda en el edificio?",
          description: "La posición influye directamente en la demanda energética.",
          required: true,
          order: 1,
          options: [
            { id: "cub-pos-1", label: "Bajo cubierta (ático)", value: "bajo_cubierta" },
            { id: "cub-pos-2", label: "Planta intermedia", value: "intermedia" },
            { id: "cub-pos-3", label: "Bajo (con local debajo)", value: "bajo" },
            { id: "cub-pos-4", label: "Unifamiliar aislada", value: "unifamiliar" },
            { id: "cub-pos-5", label: "Entre medianeras", value: "medianeras" },
          ],
        },
        {
          id: "cubierta-aislamiento",
          sectionId: "cubierta",
          type: QuestionType.RADIO,
          text: "¿Sabes si la vivienda tiene aislamiento térmico?",
          required: false,
          order: 2,
          options: [
            { id: "cub-aisl-1", label: "Sí, tiene aislamiento", value: "si_aislamiento" },
            { id: "cub-aisl-2", label: "No tiene aislamiento", value: "no_aislamiento" },
            { id: "cub-aisl-3", label: "No lo sé", value: "desconocido" },
          ],
        },
        {
          id: "cubierta-fachada",
          sectionId: "cubierta",
          type: QuestionType.RADIO,
          text: "¿Tiene la fachada cámara de aire o SATE?",
          description: "SATE = Sistema de Aislamiento Térmico por el Exterior.",
          required: false,
          order: 3,
          options: [
            { id: "cub-fach-1", label: "Sí, fachada ventilada o SATE", value: "si_sate" },
            { id: "cub-fach-2", label: "Solo cámara de aire simple", value: "camara_aire" },
            { id: "cub-fach-3", label: "No tiene aislamiento en fachada", value: "no_aislamiento" },
            { id: "cub-fach-4", label: "No lo sé", value: "desconocido" },
          ],
        },
      ],
    },

    // ── SECCIÓN 7: INSTALACIONES ──
    {
      id: "instalaciones",
      templateId: "template-segunda-opinion",
      name: "Instalaciones térmicas",
      description: "Calefacción, refrigeración y agua caliente sanitaria.",
      order: 7,
      required: true,
      estimatedTime: 5,
      questions: [
        {
          id: "instalaciones-calefaccion",
          sectionId: "instalaciones",
          type: QuestionType.SELECT,
          text: "Sistema de calefacción principal",
          required: true,
          order: 1,
          options: [
            { id: "inst-cale-1", label: "Caldera de gas natural", value: "gas_natural" },
            { id: "inst-cale-2", label: "Caldera de gasóleo", value: "gasoleo" },
            { id: "inst-cale-3", label: "Bomba de calor (aerotermia)", value: "aerotermia" },
            { id: "inst-cale-4", label: "Radiadores eléctricos", value: "electricos" },
            { id: "inst-cale-5", label: "No tiene calefacción", value: "sin_calefaccion" },
            { id: "inst-cale-6", label: "No lo sé", value: "desconocido" },
          ],
        },
        {
          id: "instalaciones-acs",
          sectionId: "instalaciones",
          type: QuestionType.RADIO,
          text: "¿Tiene placas solares térmicas para agua caliente?",
          required: false,
          order: 2,
          options: [
            { id: "inst-acs-1", label: "Sí", value: "si" },
            { id: "inst-acs-2", label: "No", value: "no" },
          ],
        },
        {
          id: "instalaciones-frio",
          sectionId: "instalaciones",
          type: QuestionType.RADIO,
          text: "¿Tiene sistema de refrigeración (aire acondicionado)?",
          required: false,
          order: 3,
          options: [
            { id: "inst-frio-1", label: "Sí, centralizado o conductos", value: "si_centralizado" },
            { id: "inst-frio-2", label: "Sí, splits individuales", value: "si_splits" },
            { id: "inst-frio-3", label: "No tiene", value: "no" },
          ],
        },
        {
          id: "instalaciones-antiguedad-caldera",
          sectionId: "instalaciones",
          type: QuestionType.SELECT,
          text: "Antigüedad aproximada de la caldera",
          required: false,
          order: 4,
          options: [
            { id: "inst-ant-1", label: "Menos de 5 años", value: "menos_5" },
            { id: "inst-ant-2", label: "5–10 años", value: "entre_5_10" },
            { id: "inst-ant-3", label: "Más de 10 años", value: "mas_10" },
            { id: "inst-ant-4", label: "No lo sé", value: "desconocido" },
          ],
        },
      ],
    },

    // ── SECCIÓN 8: FOTOGRAFÍAS ──
    {
      id: "fotografias",
      templateId: "template-segunda-opinion",
      name: "Fotografías",
      description: "Las fotos ayudan al técnico a verificar las condiciones reales del inmueble.",
      order: 8,
      required: false,
      estimatedTime: 5,
      questions: [
        {
          id: "fotografias-fachada",
          sectionId: "fotografias",
          type: QuestionType.FOTOGRAFIA,
          text: "Fotografía de la fachada del edificio",
          description: "Con una foto general de la fachada el técnico puede verificar el estado exterior.",
          required: false,
          validation: {
            maxFileSize: 10 * 1024 * 1024,
            allowedMimeTypes: ["image/jpeg", "image/png", "image/heic", "image/webp"],
          },
          order: 1,
        },
        {
          id: "fotografias-ventana",
          sectionId: "fotografias",
          type: QuestionType.FOTOGRAFIA,
          text: "Detalle de una ventana (desde dentro)",
          description: "Captura el marco y el vidrio para evaluar el tipo de carpintería.",
          required: false,
          validation: {
            maxFileSize: 10 * 1024 * 1024,
            allowedMimeTypes: ["image/jpeg", "image/png", "image/heic", "image/webp"],
          },
          order: 2,
        },
        {
          id: "fotografias-caldera",
          sectionId: "fotografias",
          type: QuestionType.FOTOGRAFIA,
          text: "Fotografía de la caldera o sistema de climatización",
          description: "Incluye la placa de características si es visible.",
          required: false,
          validation: {
            maxFileSize: 10 * 1024 * 1024,
            allowedMimeTypes: ["image/jpeg", "image/png", "image/heic", "image/webp"],
          },
          order: 3,
        },
        {
          id: "fotografias-etiqueta",
          sectionId: "fotografias",
          type: QuestionType.FOTOGRAFIA,
          text: "Fotografía de la etiqueta energética",
          description: "Si tienes la etiqueta, súbela. El sistema podrá leerla automáticamente.",
          required: false,
          validation: {
            maxFileSize: 5 * 1024 * 1024,
            allowedMimeTypes: ["image/jpeg", "image/png"],
          },
          order: 4,
        },
      ],
    },

    // ── SECCIÓN 9: OBSERVACIONES ──
    {
      id: "observaciones",
      templateId: "template-segunda-opinion",
      name: "Observaciones adicionales",
      description: "Cualquier información extra que pueda ayudar al técnico.",
      order: 9,
      required: false,
      estimatedTime: 3,
      questions: [
        {
          id: "observaciones-texto",
          sectionId: "observaciones",
          type: QuestionType.TEXTAREA,
          text: "¿Hay algo más que quieras contarnos?",
          description: "Reformas realizadas, problemas de humedades, recibos de energía elevados...",
          placeholder: "Escribe aquí cualquier detalle adicional que consideres relevante...",
          required: false,
          order: 1,
        },
        {
          id: "observaciones-archivo",
          sectionId: "observaciones",
          type: QuestionType.ARCHIVO,
          text: "Documentos adicionales",
          description: "Puedes adjuntar facturas de suministros, presupuestos de reforma u otros documentos.",
          required: false,
          validation: {
            maxFileSize: 20 * 1024 * 1024,
            allowedMimeTypes: [
              "application/pdf",
              "image/jpeg",
              "image/png",
              "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            ],
          },
          order: 2,
        },
      ],
    },

    // ── SECCIÓN 10: RESUMEN ──
    {
      id: "resumen",
      templateId: "template-segunda-opinion",
      name: "Resumen",
      description: "Revisa la información antes de enviar la solicitud.",
      order: 10,
      required: true,
      estimatedTime: 2,
      questions: [
        {
          id: "resumen-confirmacion",
          sectionId: "resumen",
          type: QuestionType.CHECKBOX,
          text: "Confirmación de envío",
          description: "Al marcar esta casilla confirmas que los datos son correctos.",
          required: true,
          order: 1,
          options: [
            {
              id: "resumen-conf-1",
              label: "Confirmo que los datos proporcionados son correctos y autorizo su uso para la elaboración del informe técnico.",
              value: "confirmado",
            },
          ],
        },
        {
          id: "resumen-firma",
          sectionId: "resumen",
          type: QuestionType.FIRMA,
          text: "Firma digital",
          description: "Firma para autorizar el inicio de la inspección técnica.",
          required: false,
          order: 2,
        },
      ],
    },
  ],
};